name: Continuous Deployment

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix develop --command cargo fmt --all -- --check
    - run: nix develop --command cargo clippy -- -D warnings
    - run: nix develop --command cargo test

  build-amd64-linux:
    needs: quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix develop --command cargo deb
    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: amd64-linux-deb
        path: 'target/debian/*'
    - run: nix develop --command cargo build --release
    - name: Zip Binaries
      run: |
        mkdir -p tmp/
        cp ./target/release/rich_pokedex tmp/
        cp ./data/pokedex.sqlite tmp/
        cp -r ./data/assets tmp/
        cd tmp
        zip -r ../rich_pokedex.zip ./*
    - name: Upload Zipped Artifact
      uses: actions/upload-artifact@v4
      with:
        name: amd64-linux-binaries
        path: 'rich_pokedex.zip'

  build-arm64-linux:
    needs: quality
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix develop --command cargo deb
    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: arm64-linux-deb
        path: 'target/debian/*'
    - run: nix develop --command cargo build --release
    - name: Zip Binaries
      run: |
        mkdir -p tmp/
        cp ./target/release/rich_pokedex tmp/
        cp ./data/pokedex.sqlite tmp/
        cp -r ./data/assets tmp/
        cd tmp
        zip -r ../rich_pokedex.zip ./*
    - name: Upload Zipped Binaries
      uses: actions/upload-artifact@v4
      with:
        name: arm64-linux-binaries
        path: 'rich_pokedex.zip'

  draft-release:
    needs: [build-amd64-linux, build-arm64-linux]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: versionNumber
        with:
          value: ${{ github.ref }}
          index_of_str: "v"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'Draft release notes: Stuff happened.'

      - uses: actions/download-artifact@v4
      - run: ls -R

      - name: Upload amd64 Linux Debian Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./amd64-linux-deb/rich-pokedex_${{ steps.versionNumber.outputs.substring }}-1_amd64.deb
          asset_name: rich-pokedex_${{ steps.versionNumber.outputs.substring }}-1_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload amd64 Linux Binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./amd64-linux-binaries/rich_pokedex.zip
          asset_name: amd64-linux
          asset_content_type: application/zip

      - name: Upload arm64 Linux Debian Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./arm64-linux-deb/rich-pokedex_${{ steps.versionNumber.outputs.substring }}-1_arm64.deb
          asset_name: rich-pokedex_${{ steps.versionNumber.outputs.substring }}-1_arm64.deb
          asset_content_type: application/zip

      - name: Upload arm64 Linux Binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./arm64-linux-binaries/rich_pokedex.zip
          asset_name: arm64-linux
          asset_content_type: application/zip
