name: Continuous Deployment

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libasound2-dev
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
    - run: cargo test

  build:
    needs: lint
    name: 'build-${{matrix.os}}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install System Dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libasound2-dev
    - run: cargo build

  flake:
    needs: build
    runs-on: [ubuntu-latest, macos-latest]
    name: Flake
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@main
    - name: Install System Dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libasound2-dev
    - run: nix build .

  debian:
    needs: build
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
    - uses: actions/checkout@v2
    - run: cargo install cargo-deb
    - name: Install System Dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libasound2-dev
    - run: cargo deb