name: Continuous Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Generate Database
      run: ./data/database.sh
    - run: nix develop --command cargo fmt --all -- --check
    - run: nix develop --command cargo clippy -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - run: ./database.sh
    - run: nix develop --command cargo test