name: Continuous Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: actions/checkout@v2
    - uses: nicknovitski/nix-develop@v1
    - run: just generate-database
    - run: just lint
    - run: just test
