name: Continuous Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Generate Database
      run: nix develop --command ./data/database.sh
    - run: nix develop --command just lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Generate Database
      run: nix develop --command ./data/database.sh
    - run: nix develop --command just test